import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id("io.github.greymagic27.McTestServer") version "1.0.0"
}

group = 'com.mrfloris'
version = '1.2.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.5-alpha")
    implementation("org.jspecify:jspecify:1.0.0")
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
        duplicatesStrategy = DuplicatesStrategy.WARN
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:deprecation']
}
